name: 'dart-action'
description: 'Use dart write action'
author: 'CaiJingLong'

inputs:
  github-token:
    description: 'The GitHub token to use for the action'
    required: true
  bin-name:
    description: 'The dart file path of the action'
    required: true
    default: bin/main.dart

runs:
  using: composite
  steps:
    - uses: subosito/flutter-action@v2
      name: Install Flutter
      with:
        channel: 'stable'
        cache: true
    - name: Show Flutter and dart version
      run: |
        dart --version
        flutter --version
      shell: bash
    - name: show the action path
      shell: bash
      run: |
        echo "runner.temp: ${{ runner.temp }}"
    - name: Install dependencies
      run: dart pub get
      working-directory: ${{ runner.temp }}
      shell: bash
    - name: Run dart
      run: dart run "${{ runner.temp }}/${{ inputs.bin-name }}"
      shell: bash