name: "Check action"

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: dart-action/dart_action_template@main
        name: Run action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}